<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

// for debugging
$wgShowSQLErrors        = true;
$wgDebugDumpSql = true;

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.

$IP = "/home/alluminati/alluminati.org/wik";
ini_set( "include_path", ".:$IP:$IP/includes:$IP/languages" );
require_once( "includes/DefaultSettings.php" );

$wgDebugLogFile = "$IP/debug.log";

# If PHP's memory limit is very low, some operations may fail.
ini_set( 'memory_limit', '60M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
} elseif ( empty( $wgConfiguring ) ) {
	## Compress output if the browser supports it
	if( !ini_get( 'zlib.output_compression' ) ) ob_start( 'ob_gzhandler' );
}

$wgSitename         = “Chi Wiki";
$wgScriptPath	    = "/wik";
$wgScript           = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";

## If using PHP as a CGI module, use the ugly URLs
$wgArticlePath = "/wiki/$1";
#$wgArticlePath      = "$wgScript?title=$1";

$wgStylePath        = "$wgScriptPath/skins";
$wgStyleDirectory   = "$IP/skins";
#$wgLogo             = "$wgStylePath/common/images/wiki.png";
$wgLogo = "$wgScriptPath/iphiwikilogo.png";

$wgEmergencyContact = "admin@apo-x.org";
$wgPasswordSender	= "admin@apo-x.org";

## Database settings.

/** Get database info from centralized file */
require( '../include/connection.inc.php' );

$wgDBserver         = DB_HOST;
$wgDBname           = DB_NAME;
$wgDBuser           = DB_USER;
$wgDBpassword       = DB_PASS;
$wgDBprefix         = "wiki_";

## Settings for uploads.
$wgEnableUploads = true;
$wgUploadPath       = "$wgScriptPath/images";
$wgUploadDirectory  = "$IP/images";
$wgCheckFileExtensions = true;
$wgVerifyMimeType = true;
# Allowed file types for uploading.
$wgFileExtensions = array('png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx', 'pptx', 'ps', 'zip', 'rar');
$wgStrictFileExtensions = true;
# Disallowed file types for uploading based on extension.
$wgFileBlacklist = array(
  # HTML may contain cookie-stealing JavaScript and web bugs
  'html', 'htm', 'js', 'jsb', 'mhtml', 'mht',
  # PHP scripts may execute arbitrary code on the server
  'php', 'phtml', 'php3', 'php4', 'php5', 'phps',
  # Other types that may be interpreted by some servers
  'shtml', 'jhtml', 'pl', 'py', 'cgi',
  # May contain harmful executables for Windows victims
  'exe', 'scr', 'dll', 'msi', 'vbs', 'bat', 'com', 'pif', 'cmd', 'vxd', 'cpl'
);
# Disallowed file types for uploading based on mime type.
$wgMimeTypeBlacklist= array(
	# HTML may contain cookie-stealing JavaScript and web bugs
	'text/html', 'text/javascript', 'text/x-javascript',  'application/x-shellscript',
	# PHP scripts may execute arbitrary code on the server
	'application/x-php', 'text/x-php',
	# Other types that may be interpreted by some servers
	'text/x-python', 'text/x-perl', 'text/x-bash', 'text/x-sh', 'text/x-csh',
	# Windows metafile, client-side vulnerability on some systems
	'application/x-msmetafile',
	# A ZIP file may be a valid Java archive containing an applet which exploits the
	# same-origin policy to steal cookies      
	'application/zip'
);

## To allow SQL queries through the wiki's Special:Askaql page,
## uncomment the next lines. THIS IS VERY INSECURE. If you want
## to allow semipublic read-only SQL access for your sysops,
## you should define a MySQL user with limited privileges.
## See MySQL docs: http://www.mysql.com/doc/en/GRANT.html
#
# $wgAllowSysopQueries = true;
# $wgDBsqluser        = "sqluser";
# $wgDBsqlpassword    = "sqlpass";

# If you're on MySQL 3.x, this next line must be FALSE:
$wgDBmysql4 = $wgEnablePersistentLC = false;

## Shared memory settings
$wgUseMemCached = false;
$wgMemCachedServers = array();
#$wgUseTurckShm = function_exists( 'mmcache_get' ) && php_sapi_name() == 'apache';

## Image settings.
$wgAllowExternalImages = true;
$wgUseImageResize		= true;
#$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
# $wgUseTeX			= true;
$wgMathPath         = "{$wgUploadPath}/math";
$wgMathDirectory    = "{$wgUploadDirectory}/math";
$wgTmpDirectory     = "{$wgUploadDirectory}/tmp";

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";
$wgUseLatin1 = false;

$wgProxyKey = "e41c81bfb295bddae63731ffbe687e3a0d5a2aec75cb7beaba674b168ae8d300";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
 $wgDefaultSkin = 'vector';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgLocaltimezone = 'PST8PDT';
$wgLocalTZoffset = '-7:00';

## Disable anonymous edits
$wgGroupPermissions['*']['edit'] = false;
## No user tools for anonymous users
$wgShowIPinHeader = false;
## Log IP's of editors
$wgPutIPinRC = true;

#user stuff
$wgDefaultUserOptions['skin'] = "vector";
$wgDefaultUserOptions['underline'] = "0";

#Extensions
require_once("$IP/extensions/Cite/Cite.php");
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );
$wgPFEnableStringFunctions = true;
require_once("extensions/Winter.php");
include_once("$IP/extensions/SemanticMediaWiki/SemanticMediaWiki.php");
enableSemantics(‘alluminati.org');
include_once("$IP/extensions/SemanticForms/includes/SF_Settings.php");
require_once("$IP/extensions/ConfirmEdit/ConfirmEdit.php");
require_once("$IP/extensions/ConfirmAccount/SpecialConfirmAccount.php");

#ConfirmAccount settings
$wgMakeUserPageFromBio = false;
$wgAutoWelcomeNewUsers = false;
$wgUseRealNamesOnly = false;
$wgAccountRequestExtraInfo = false;
$wgAccountRequestMinWords = 0;
$wgAllowRealName = false;
$wgConfirmAccountSaveInfo = false;
?>
